# Generated by Django 4.2.4 on 2023-08-16 16:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('date_creat', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('F', 'filosofia'), ('T', 'tecnologia'), ('R', 'Regras')], max_length=20)),
                ('thumb_image', models.ImageField(upload_to='App/static/thumb')),
            ],
        ),
    ]
