# Generated by Django 4.2.4 on 2023-08-19 12:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('date_creat', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Filosofia', 'filosofia'), ('Tecnologia', 'tecnologia'), ('Regras', 'Regras')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
